<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'AppUser\Module'                        => __DIR__ . '/Module.php',
    'AppUser\Controller\IndexController' => __DIR__ . '/src/AppUser/Controller/IndexController.php',
);
